name: Generate 3D Contribution Graph
on:
  schedule: # execute every day
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Generate 3D Contribution Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: JamshedAli18
        with:
          username: JamshedAli18
      
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update 3D contribution graph"
          git push
